services:
    mailgun_admin.listener.send:
        class: Copromatic\MailgunAdminBundle\Listener\Send
        arguments: ['@doctrine', '@logger']
        tags:
            - { name: swiftmailer.mailer.plugin }