services:
    mailgun_admin.listener.send:
        class: Copromatic\MailgunAdminBundle\Listener\Send
        arguments: ['@mailgun_admin.entity_manager']
        tags:
            - { name: swiftmailer.mailer.plugin }
