services:
    copromatic_mailgun_admin.listener.send:
        class: Copromatic\MailgunAdminBundle\Listener\Send
        arguments: ['@copromatic_mailgun_admin.entity_manager', '@logger']
        tags:
            - { name: swiftmailer.mailer.plugin }